### ISSUE TITLE
Provide a way track events without the controller layer

### ISSUE THREAD

**Issue by raine** [zevarito/mixpanel#11]
Mixpanel::Tracker depends on request.env being available, yeah? I wanted to track events in an observer and it wasn't possible.

**Comment by zevarito** [comment]
That is correct, AR callbacks and observers have nothing to do with a request.

For example, you cannot access current_user from an observer, that is right in the point of view of MVC.

I don't know what exactly are you trying to do, but for example...

If your model persist which user has created the object, then in your observer you can access to the user that has been created the object from a request.

IMHO while seems to be much more easy and decoupled to use Mixpanel from observers is better and more realistic to make it from controllers, since those activity comes from a request.

Anyway you can work around to have all what you need in observers, but personally I try to avoid ugly hacks such as User.current

Again, I am not sure what you are trying to do, this is strictly related to MVC, but always there is a work around.

**Comment by zevarito** [comment]
Well, I am reading my comment and I think I've answered another question than yours :P

Please take a look at: https://github.com/zevarito/mixpanel/blob/master/lib/mixpanel/tracker.rb

You should be able to instantiate Mixpanel::Tracker from an observer "faking" (mocking) -env- but off course you will lose request information such as IP address of the person who makes the action.
