### ISSUE TITLE
Please support https

### ISSUE THREAD

**Issue by danielribeiro** [zevarito/mixpanel#55]
The way it is done [now](https://github.com/zevarito/mixpanel/blob/master/lib/mixpanel/event.rb#L3), all data is passed in plain sight.

**Comment by danielribeiro** [comment]
Well, I ended up fixing a bit their code: https://gist.github.com/4192201

**Comment by zevarito** [comment]
Hi @danielribeiro,

That should probably end being a clever solution ;)

Anyway, meanwhile, if you still want to use the gem you can override `track` url option as it shows here:

https://github.com/zevarito/mixpanel#track-events-directly

If you want to contribute to this development you should look at this two files:

https://github.com/zevarito/mixpanel/blob/master/lib/mixpanel/event.rb#L3
https://github.com/zevarito/mixpanel/blob/master/lib/mixpanel/tracker.rb#L16

Probably this all isn't needed since you already figured out, I wouldn't be able to do this
because I just realized that this gem is having active_support as dependency, need to
solve it first :)

https://github.com/zevarito/mixpanel/blob/master/lib/mixpanel/event.rb#L25
